- name: Controller setup
  hosts: localhost
  gather_facts: no
  become: true
  tasks:
    - name: Ensure Endpoint repository is installed
      yum_repository:
        name: endpoint
        description: End Point repository (required for installing Git in version 2.x)
        baseurl: https://packages.endpoint.com/rhel/$releasever/os/$basearch/
        gpgkey: https://packages.endpoint.com/endpoint-rpmsign-7.pub
        gpgcheck: yes
        enabled: yes
        state: present
    - name: Ensure Jenkins repository is installed
      yum_repository:
        name: jenkins
        description: Official Jenkins Yum Repo
        baseurl: http://pkg.jenkins.io/redhat-stable
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        gpgcheck: yes
        enabled: yes
        state: present
    - name: Install OpenJDK, Git and Jenkins
      yum:
        name:
          - java-1.8.0-openjdk
          - java-1.8.0-openjdk-devel
          - git
          - jenkins
        state: latest
    - name: Enable and Start the Jenkins Service
      service:
        name: jenkins
        enabled: yes
        state: started
