- name: Controller setup
  hosts: localhost
  gather_facts: yes
  become: true
  vars:
    kv_uri: https://oscm-vault.vault.azure.net/
  tasks:
    - name: Install OpenJDK, Git
      apt:
        update_cache: yes
        name:
          - openjdk-8-jdk
          - git
        state: latest
        
    - name: Include vars for key vault
      include_vars:
       file: vaultList.yml
       name: vaultList
       
    - name: Source the bashrc file
      ansible.builtin.shell: "echo $AZURE_TENANT_ID"

    - name: Set facts
      set_fact:
       az_object_id: "{{ lookup('env', 'AZURE_OBJECT_ID') }}"
       az_tenant_id: "{{ lookup('env', 'AZURE_TENANT_ID') }}"
       az_client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
       az_sub_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
       az_secret: "{{ lookup('env', 'AZURE_CLIENT_SECRET') }}"
       
    - name: Print return information from the previous task
      ansible.builtin.debug:
         var: az_secret

    - name: Get latest version of a secret
      azure.azcollection.azure_rm_keyvaultsecret_info:
        subscription_id: "{{ az_sub_id }}"
        client_id: "{{ az_client_id }}"
        tenant: "{{ az_tenant_id }}"
        secret: "{{ az_secret }}"
        vault_uri: "{{ kv_uri }}"
        name: "{{ item }}"
      register: secret
      with_items:
            - "{{ vaultList.vault }}"


    - include_tasks: paths.yml
      loop: "{{ vaultList.vault }}"
      loop_control:
         loop_var: "vault_key"
         
    - name: Install prerequisites for Docker repository
      apt:
        name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg


    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
    - name: Install Docker CE
      apt:
        name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        state: present
        update_cache: yes
