#*****************************************************************************
#*                                                                           *
#* Copyright FUJITSU LIMITED 2021                                            *                                                                     *
#* Creation Date: 22-04-2021                                                 *
#*                                                                           *
#*****************************************************************************

jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: falsea
  # label the controller
  labelAtoms:
  - name: "Controller"
  - name: "agent1"
  - name: "linux"
  - name: "master"
  labelString: "Controller"
  markupFormatter: "plainText"
  mode: EXCLUSIVE
  myViewsTabBar: "standard"
  nodes:
  - permanent:
      labelString: "192.168.32.115 linux"
      launcher:
        command:
          # the command how to connect the controller to the jenkins master
          command: "ssh -i /var/lib/jenkins/agent1_cert vagrant@192.168.32.115 -o StrictHostKeyChecking=no\
            \ \"sudo su -s /bin/bash jenkins -c 'cd /var/lib/jenkins && curl -O http://192.168.32.113:8080/jnlpJars/agent.jar\
                \ && java -jar agent.jar'\""
      mode: EXCLUSIVE
      name: "agent1"
      remoteFS: "/var/lib/jenkins"
      retentionStrategy: "always"
  numExecutors: 0
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        name: "admin"
        properties:
        - "apiToken"
        - "mailer"
        - preferredProvider:
            providerId: "default"
  slaveAgentPort: -1
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  copyartifact:
    mode: PRODUCTION
  sSHD:
    port: -1
unclassified:
  artifactoryBuilder:
    jfrogPipelinesServer:
      bypassProxy: false
      connectionRetries: 3
      credentialsConfig:
        ignoreCredentialPluginDisabled: true
        overridingCredentials: false
        password: "{AQAAABAAAAAQ2HdyjzJ8rkuFF3uPSobSvaVGVh6sR/t3hs1vGw5YTpI=}"
        username: "****"
      timeout: 300
    useCredentialsPlugin: false
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitSCM:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  ivyBuildTrigger:
    extendedVersionMatching: false
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "Adresse nicht konfiguriert <nobody@nowhere>"
    url: "http://192.168.32.113:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  mavenModuleSet:
    localRepository: "default"
  pollSCM:
    pollingThreadCount: 10
  upstream:
    globalUpstreamFilterStrategy: UseOldest
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
